baseURL = "https://btctranscripts.com/"
languageCode = "en-us"

theme = "ace-documentation"
ignoreFiles = [ "README.md", "LICENSE.md" ]

DefaultContentLanguage = "en"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  speaker = 'speakers'

[module]
  [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "prebuild/public/tags"
    target = "content/tags"

  [[module.mounts]]
    source = "tags"
    target = "content/tags"

[languages]
  [languages.en]
    title = "₿itcoin Transcripts"
    languageName = "English"
    weight = 1
  [languages.es]
    title = "Transcripciones de ₿itcoin"
    languageName = "Español"
    weight = 2
  [languages.pt]
    title = "Transcrições de ₿itcoin"
    languageName = "Português"
    weight = 2
  [languages.zh]
    title = "₿itcoin 记录稿"
    languageName = "简体中文"
    weight = 3

[mediaTypes."application/json"]
  suffixes = ["json"]

[outputFormats.Index]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true

[outputFormats.Status]
  mediaType = "application/json"
  baseName = "status"
  isPlainText = true

[outputFormats.Directories]
  mediaType = "application/json"
  baseName = "directories"
  isPlainText = true

[outputFormats.Sources]
  mediaType = "application/json"
  baseName = "sources"
  isPlainText = true

[outputs]
    home = [ "HTML", "Status", "Directories", "Sources", "Index"]
    page = [ "HTML"]

[params]
    ordersectionsby = "title"
    disableReadmoreNav = true
    menushortcutsnewtab = false
    custom_js = ["js/custom.js"]
    custom_css = ["scss/custom.scss"]
    images = ["images/btctranscripts.png"]
    description = "A treasure trove of ₿itcoin transcripts (mostly recorded by @kanzure)"
    
[markup]
  [markup.tableOfContents]
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe = true

[[languages.en.menu.shortcuts]]
    name = "es"
    url = "/es"
    weight = 1
[[languages.en.menu.shortcuts]]
    name = "pt"
    url = "/pt"
    weight = 2
[[languages.en.menu.shortcuts]]
    name = "zh"
    url = "/zh"
    weight = 3
[[languages.es.menu.shortcuts]]
    name = "en"
    url = "/en"
    weight = 1
[[languages.es.menu.shortcuts]]
    name = "pt"
    url = "/pt"
    weight = 2
[[languages.es.menu.shortcuts]]
    name = "zh"
    url = "/zh"
    weight = 3
[[languages.pt.menu.shortcuts]]
    name = "en"
    url = "/en"
    weight = 1
[[languages.pt.menu.shortcuts]]
    name = "es"
    url = "/es"
    weight = 2
[[languages.pt.menu.shortcuts]]
    name = "zh"
    url = "/zh"
    weight = 3
[[languages.zh.menu.shortcuts]]
    name = "en"
    url = "/en"
    weight = 1
[[languages.zh.menu.shortcuts]]
    name = "es"
    url = "/es"
    weight = 2
[[languages.zh.menu.shortcuts]]
    name = "pt"
    url = "/pt"
    weight = 3    